import type { TopicExtras } from "../types";
// AUTO-GENERATED by scripts/gen-extras-index.mjs — do not edit by hand.
import { extras as e_bio_cells } from "./bio-cells";
import { extras as e_bio_coordination } from "./bio-coordination";
import { extras as e_bio_disease_immunity } from "./bio-disease-immunity";
import { extras as e_bio_ecology } from "./bio-ecology";
import { extras as e_bio_enzymes } from "./bio-enzymes";
import { extras as e_bio_gas_respiration } from "./bio-gas-respiration";
import { extras as e_bio_human_nutrition } from "./bio-human-nutrition";
import { extras as e_bio_inheritance } from "./bio-inheritance";
import { extras as e_bio_molecules } from "./bio-molecules";
import { extras as e_bio_plant_nutrition } from "./bio-plant-nutrition";
import { extras as e_bio_reproduction } from "./bio-reproduction";
import { extras as e_bio_transport_animals } from "./bio-transport-animals";
import { extras as e_bio_transport_cell } from "./bio-transport-cell";
import { extras as e_bio_transport_plants } from "./bio-transport-plants";
import { extras as e_chem_acids_bases } from "./chem-acids-bases";
import { extras as e_chem_analysis } from "./chem-analysis";
import { extras as e_chem_atoms } from "./chem-atoms";
import { extras as e_chem_bonding } from "./chem-bonding";
import { extras as e_chem_electrochemistry } from "./chem-electrochemistry";
import { extras as e_chem_energetics } from "./chem-energetics";
import { extras as e_chem_environment } from "./chem-environment";
import { extras as e_chem_metals } from "./chem-metals";
import { extras as e_chem_organic } from "./chem-organic";
import { extras as e_chem_particles } from "./chem-particles";
import { extras as e_chem_periodic } from "./chem-periodic";
import { extras as e_chem_rates } from "./chem-rates";
import { extras as e_chem_stoichiometry } from "./chem-stoichiometry";
import { extras as e_phys_electricity } from "./phys-electricity";
import { extras as e_phys_energy } from "./phys-energy";
import { extras as e_phys_forces } from "./phys-forces";
import { extras as e_phys_magnetism } from "./phys-magnetism";
import { extras as e_phys_motion } from "./phys-motion";
import { extras as e_phys_nuclear } from "./phys-nuclear";
import { extras as e_phys_sound_em } from "./phys-sound-em";
import { extras as e_phys_space } from "./phys-space";
import { extras as e_phys_thermal } from "./phys-thermal";
import { extras as e_phys_waves } from "./phys-waves";

export const EXTRAS_LIST: TopicExtras[] = [
  e_bio_cells,
  e_bio_coordination,
  e_bio_disease_immunity,
  e_bio_ecology,
  e_bio_enzymes,
  e_bio_gas_respiration,
  e_bio_human_nutrition,
  e_bio_inheritance,
  e_bio_molecules,
  e_bio_plant_nutrition,
  e_bio_reproduction,
  e_bio_transport_animals,
  e_bio_transport_cell,
  e_bio_transport_plants,
  e_chem_acids_bases,
  e_chem_analysis,
  e_chem_atoms,
  e_chem_bonding,
  e_chem_electrochemistry,
  e_chem_energetics,
  e_chem_environment,
  e_chem_metals,
  e_chem_organic,
  e_chem_particles,
  e_chem_periodic,
  e_chem_rates,
  e_chem_stoichiometry,
  e_phys_electricity,
  e_phys_energy,
  e_phys_forces,
  e_phys_magnetism,
  e_phys_motion,
  e_phys_nuclear,
  e_phys_sound_em,
  e_phys_space,
  e_phys_thermal,
  e_phys_waves,
];
