import type { TopicExtras } from "../types";

export const extras: TopicExtras = {
  topicId: "phys-magnetism",
  hook:
    "Earth is wrapped in an invisible magnetic shield stretching tens of thousands of kilometres into space — without it, the solar wind would strip away our atmosphere and oceans just as it did to Mars. Every compass needle on the planet is silently pointing to the evidence of that shield right now.",
  didYouKnow: [
    "Earth's magnetic field is generated by convection currents of liquid iron in the outer core, roughly 2 900 km below your feet — a planetary-scale dynamo powered by the heat of radioactive decay and residual heat from Earth's formation.",
    "The geographic North Pole and the magnetic north pole are not the same place. In 2024 the magnetic north pole sits in the Canadian Arctic and drifts by about 50 km per year towards Siberia.",
    "Earth's magnetic field reverses polarity on average every 200 000–300 000 years. The last reversal (the Brunhes–Matuyama reversal) occurred about 780 000 years ago, so we are statistically overdue — though reversals take thousands of years and do not happen overnight.",
    "Maglev trains in Japan (SCMaglev) use superconducting electromagnets to levitate the train about 10 cm above the track, eliminating friction and allowing speeds exceeding 600 km/h in test runs.",
    "The aurora borealis (northern lights) is caused by charged particles from the solar wind spiralling along magnetic field lines and exciting atmospheric gases — oxygen glows green and red, nitrogen glows blue and purple.",
    "A magnetar (a type of neutron star) can have a magnetic field about 10^15 times stronger than Earth's — so powerful that within 1 000 km it would disrupt the atoms in your body and erase every credit card on Earth.",
  ],
  experiments: [
    {
      title: "Map a Magnetic Field with Iron Filings",
      materials: [
        "A bar magnet",
        "A sheet of white A4 paper",
        "Iron filings (available cheaply online; or carefully collect metal shavings from a hardware store)",
        "A thin book or flat board to place under the paper (to keep it level)",
        "Optional: small plotting compass to trace field lines",
      ],
      steps: [
        "Place the bar magnet on the book or board and lay the sheet of paper flat on top so the magnet is underneath.",
        "Gently sprinkle a thin, even layer of iron filings over the paper directly above and around the magnet.",
        "Gently tap the edges of the paper a few times to allow the filings to settle and align with the magnetic field.",
        "Observe and sketch the pattern — note the concentration of filings at the poles and the curved lines flowing from north to south.",
        "Optionally, remove the filings, draw dots every 2 cm over the paper, place the plotting compass at each dot, and mark where the north-seeking end points — then join the arrows to trace field lines.",
        "Repeat with two bar magnets placed with like poles facing each other, then unlike poles facing each other, and compare the patterns.",
      ],
      science:
        "Iron filings are tiny magnets themselves. Each filing experiences a torque from the external field and rotates until it lies along a field line, like a miniature compass needle. The density of filings indicates field strength — fields are strongest (most concentrated) near the poles. The curved lines emerging from the north pole and entering the south pole are the conventional magnetic field lines, showing the direction a free north pole would travel. The neutral point between two like poles (where filings are sparse) shows that the two fields cancel at that location.",
      safety:
        "Keep iron filings away from eyes and nose — work outdoors or in a well-ventilated area. Wash hands afterwards. Keep the magnet away from electronic devices, bank cards, and hard drives.",
    },
    {
      title: "Make a Floating Compass (Temporary Magnetism)",
      materials: [
        "A sewing needle",
        "A bar magnet or strong fridge magnet",
        "A small piece of cork, foam, or a leaf",
        "A bowl of still water",
        "Optional: a real compass to check your result",
      ],
      steps: [
        "Stroke the needle along the magnet in one direction only (always the same direction, always lifting the needle off before the return stroke) about 50 times.",
        "Float the small piece of cork or foam on the still water in the bowl.",
        "Gently lay the magnetised needle on the cork or foam so it can rotate freely.",
        "Observe which direction the needle settles — it should align roughly north–south.",
        "Bring the magnet near the bowl and watch how the needle responds to prove it has been magnetised.",
        "Check your reading against a real compass if available.",
      ],
      science:
        "The needle is made of steel, a ferromagnetic material containing magnetic domains — regions where atomic magnetic moments are aligned. Stroking it repeatedly with a magnet nudges the domains into alignment in one direction, producing a net magnetic moment and turning the needle into a permanent magnet. Floating it removes friction so it can freely align with Earth's magnetic field, just as a commercial compass needle does. This is also how ancient mariners magnetised iron needles by stroking them with naturally occurring lodestone (magnetite).",
      safety: "Handle the needle with care to avoid skin puncture. Keep the magnet away from electronic devices.",
    },
  ],
};
